Namespace Inspection

	''' <summary>Enum representing different Analyser Entities Types.</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:51:42</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Inspection\Enums\AnalyserType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Inspection\Enums\AnalyserType.tt", "1")> _
	Public Enum AnalyserType As System.Int32

		''' <summary>AssemblyAnalyser</summary>
		AssemblyAnalyser = 1

		''' <summary>TypeAnalyser</summary>
		TypeAnalyser = 2

		''' <summary>AttributeAnalyser</summary>
		AttributeAnalyser = 3

		''' <summary>MemberAnalyser</summary>
		MemberAnalyser = 4

		''' <summary>MethodAnalyser</summary>
		MethodAnalyser = 5

		''' <summary>FolderAnalyser</summary>
		FolderAnalyser = 6

		''' <summary>ExceptionAnalyser</summary>
		ExceptionAnalyser = 7

		''' <summary>ConstructorAnalyser</summary>
		ConstructorAnalyser = 8

	End Enum

End Namespace