Namespace Inspection

	''' <summary>Enum representing Array/Collection/List Actions.</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:51:42</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Inspection\Enums\CollectionAction.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Inspection\Enums\CollectionAction.tt", "1")> _
	Public Enum CollectionAction As System.Int32

		''' <summary>RemoveObject</summary>
		RemoveObject = 1

		''' <summary>RemoveObjects</summary>
		RemoveObjects = 2

		''' <summary>RemoveIndex</summary>
		RemoveIndex = 3

		''' <summary>AddObject</summary>
		AddObject = 4

		''' <summary>AddObjects</summary>
		AddObjects = 5

	End Enum

End Namespace