Namespace Inspection

	''' <summary>Enum Representing Type Member Visibility.</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:51:45</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Inspection\Enums\MemberVisibility.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Inspection\Enums\MemberVisibility.tt", "1")> _
	<Flags()> _
	Public Enum MemberVisibility As System.Int32

		''' <summary>Member has Private Visibility.</summary>
		[Private] = 1

		''' <summary>Member has Protected Visibility.</summary>
		[Protected] = 2

		''' <summary>Member has Friend Visibility.</summary>
		[Friend] = 4

		''' <summary>Member has Public Visibility.</summary>
		[Public] = 8

		''' <summary>Member has Protected Friend Visibility.</summary>
		ProtectedFriend = 6

		''' <summary>Members has Non-Public Visibility.</summary>
		NonPublic = 3

		''' <summary>All Flags</summary>
		All = [Private] Or _
			[Protected] Or _
			[Friend] Or _
			[Public] Or _
			ProtectedFriend Or _
			NonPublic

	End Enum

End Namespace