Namespace Inspection

	''' <summary>Enum Representing Type Member Accessiblity.</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:51:43</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Inspection\Enums\MemberAccessibility.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Inspection\Enums\MemberAccessibility.tt", "1")> _
	<Flags()> _
	Public Enum MemberAccessibility As System.Int32

		''' <summary>Readable Member.</summary>
		Readable = 1

		''' <summary>Writable Member.</summary>
		Writable = 2

		''' <summary>Read Only Member.</summary>
		[ReadOnly] = 4

		''' <summary>Write Only Member.</summary>
		[WriteOnly] = 8

		''' <summary>Read/Write Member.</summary>
		ReadWrite = 16

		''' <summary>All Flags</summary>
		All = Readable Or _
			Writable Or _
			[ReadOnly] Or _
			[WriteOnly] Or _
			ReadWrite

	End Enum

End Namespace