Namespace Inspection

	''' <summary>Enum Representing Type Member Location.</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:51:43</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Inspection\Enums\MemberLocation.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Inspection\Enums\MemberLocation.tt", "1")> _
	<Flags()> _
	Public Enum MemberLocation As System.Int32

		''' <summary>Member is located as an Instance Member.</summary>
		Instance = 1

		''' <summary>Member is located as a Static Member.</summary>
		[Static] = 2

		''' <summary>All Flags</summary>
		All = Instance Or _
			[Static]

	End Enum

End Namespace