Namespace Comparison

	''' <summary>This attribute indicates a property that will be used when calling IComparable Methods.</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:48:48</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Comparison\Attributes\ComparableAttribute.tt</generator-source>
	''' <generator-template>Text-Templates\Classes\VB_Object.tt</generator-template>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Comparison\Attributes\ComparableAttribute.tt", "1")> _
	<AttributeUsageAttribute(AttributeTargets.[Property] Or AttributeTargets.[Field], _
		AllowMultiple:=False, Inherited:=False)> _
	Partial Public Class ComparableAttribute
		Inherits Attribute

		#Region " Public Constructors "

			''' <summary>Default Constructor</summary>
			Public Sub New()

				MyBase.New()

			End Sub

		#End Region

		#Region " Class Plumbing/Interface Code "

			#Region " Attributable Implementation "

				#Region " Public Shared Methods "

					Public Shared Function GetMember( _
						ByVal onType As Type _
					) As Leviathan.Inspection.MemberAnalyser

						Return GetSingleObject(GetMembers(onType))

					End Function

					Public Shared Function GetMembers( _
						ByVal onType As Type _
					) As Leviathan.Inspection.MemberAnalyser()

						Return Leviathan.Inspection.TypeAnalyser.GetInstance(onType) _
							.ExecuteQuery(Leviathan.Inspection.AnalyserQuery.QUERY_MEMBERS_READABLE _
								.SetPresentAttribute(GetType(ComparableAttribute)) _
						)

					End Function

				#End Region

			#End Region

		#End Region

	End Class

End Namespace