Namespace Files

	''' <summary>Enum Representing Command Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:50:36</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Files\Enums\ComplexPropagationFlags.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Files\Enums\ComplexPropagationFlags.tt", "1")> _
	<Flags()> _
	Public Enum ComplexPropagationFlags As System.Int32

		''' <summary>None</summary>
		None = 0

		''' <summary>TargetDirectory</summary>
		TargetDirectory = 1

		''' <summary>ChildDirectory</summary>
		ChildDirectory = 2

		''' <summary>DescendantDirectory</summary>
		DescendantDirectory = 4

		''' <summary>ChildFile</summary>
		ChildFile = 8

		''' <summary>DescendantFile</summary>
		DescendantFile = 16

		''' <summary>All Flags</summary>
		All = None Or _
			TargetDirectory Or _
			ChildDirectory Or _
			DescendantDirectory Or _
			ChildFile Or _
			DescendantFile

	End Enum

End Namespace