Namespace Configuration

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:50:05</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Configuration\Exceptions\ParsingException.tt</generator-source>
	''' <generator-template>Text-Templates\Classes\VB_Object.tt</generator-template>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Configuration\Exceptions\ParsingException.tt", "1")> _
	Partial Public Class ParsingException
		Inherits Exception

		#Region " Public Constructors "

			''' <summary>Default Constructor</summary>
			Public Sub New()

				MyBase.New()

			End Sub

			''' <summary>Parametered Constructor (1 Parameters)</summary>
			Public Sub New( _
				ByVal _Argument As String _
			)

				MyBase.New()

				Argument = _Argument

			End Sub

			''' <summary>Parametered Constructor (2 Parameters)</summary>
			Public Sub New( _
				ByVal _Argument As String, _
				ByVal _Type As System.Type _
			)

				MyBase.New()

				Argument = _Argument
				[Type] = _Type

			End Sub

		#End Region

		#Region " Public Constants "

			''' <summary>Public Shared Reference to the Name of the Property: Argument</summary>
			''' <remarks></remarks>
			Public Const PROPERTY_ARGUMENT As String = "Argument"

			''' <summary>Public Shared Reference to the Name of the Property: Type</summary>
			''' <remarks></remarks>
			Public Const PROPERTY_TYPE As String = "Type"

		#End Region

		#Region " Private Variables "

			''' <summary>Private Data Storage Variable for Property: Argument</summary>
			''' <remarks></remarks>
			Private m_Argument As String

			''' <summary>Private Data Storage Variable for Property: Type</summary>
			''' <remarks></remarks>
			Private m_Type As System.Type

		#End Region

		#Region " Public Properties "

			''' <summary>Provides Access to the Property: Argument</summary>
			''' <remarks></remarks>
			Public Property Argument() As String
				Get
					Return m_Argument
				End Get
				Set(value As String)
					m_Argument = value
				End Set
			End Property

			''' <summary>Provides Access to the Property: Type</summary>
			''' <remarks></remarks>
			Public Property [Type]() As System.Type
				Get
					Return m_Type
				End Get
				Set(value As System.Type)
					m_Type = value
				End Set
			End Property

		#End Region

	End Class

End Namespace