''' <summary>Holds the Assembly Configuration</summary>
''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
''' <generator-date>10/02/2014 15:37:16</generator-date>
''' <generator-functions>1</generator-functions>
''' <generator-source>Leviathan\Assembly\AssemblyConfig.tt</generator-source>
''' <generator-template>Text-Templates\Classes\VB_Object.tt</generator-template>
''' <generator-version>1</generator-version>
<System.CodeDom.Compiler.GeneratedCode("Leviathan\Assembly\AssemblyConfig.tt", "1")> _
Partial Public Class AssemblyConfig
	Inherits System.Object

	#Region " Public Constructors "

		''' <summary>Default Constructor</summary>
		Public Sub New()

			MyBase.New()

			m_Started = DateTime.Now
			m_CommandClasses = New CommandInterrogatedClass() {}
			m_InterrogatedCommands = New CommandInterrogated() {}
		End Sub

		''' <summary>Parametered Constructor (1 Parameters)</summary>
		Public Sub New( _
			ByVal _Started As System.DateTime _
		)

			MyBase.New()

			Started = _Started

			m_CommandClasses = New CommandInterrogatedClass() {}
			m_InterrogatedCommands = New CommandInterrogated() {}
		End Sub

		''' <summary>Parametered Constructor (2 Parameters)</summary>
		Public Sub New( _
			ByVal _Started As System.DateTime, _
			ByVal _Matcher As ICommandsMatcher _
		)

			MyBase.New()

			Started = _Started
			Matcher = _Matcher

			m_CommandClasses = New CommandInterrogatedClass() {}
			m_InterrogatedCommands = New CommandInterrogated() {}
		End Sub

		''' <summary>Parametered Constructor (3 Parameters)</summary>
		Public Sub New( _
			ByVal _Started As System.DateTime, _
			ByVal _Matcher As ICommandsMatcher, _
			ByVal _Sources As ICommandsProvider() _
		)

			MyBase.New()

			Started = _Started
			Matcher = _Matcher
			Sources = _Sources

			m_CommandClasses = New CommandInterrogatedClass() {}
			m_InterrogatedCommands = New CommandInterrogated() {}
		End Sub

		''' <summary>Parametered Constructor (4 Parameters)</summary>
		Public Sub New( _
			ByVal _Started As System.DateTime, _
			ByVal _Matcher As ICommandsMatcher, _
			ByVal _Sources As ICommandsProvider(), _
			ByVal _CommandClasses As CommandInterrogatedClass() _
		)

			MyBase.New()

			Started = _Started
			Matcher = _Matcher
			Sources = _Sources
			CommandClasses = _CommandClasses

			m_InterrogatedCommands = New CommandInterrogated() {}
		End Sub

		''' <summary>Parametered Constructor (5 Parameters)</summary>
		Public Sub New( _
			ByVal _Started As System.DateTime, _
			ByVal _Matcher As ICommandsMatcher, _
			ByVal _Sources As ICommandsProvider(), _
			ByVal _CommandClasses As CommandInterrogatedClass(), _
			ByVal _InterrogatedCommands As CommandInterrogated() _
		)

			MyBase.New()

			Started = _Started
			Matcher = _Matcher
			Sources = _Sources
			CommandClasses = _CommandClasses
			InterrogatedCommands = _InterrogatedCommands

		End Sub

		''' <summary>Parametered Constructor (6 Parameters)</summary>
		Public Sub New( _
			ByVal _Started As System.DateTime, _
			ByVal _Matcher As ICommandsMatcher, _
			ByVal _Sources As ICommandsProvider(), _
			ByVal _CommandClasses As CommandInterrogatedClass(), _
			ByVal _InterrogatedCommands As CommandInterrogated(), _
			ByVal _Finished As System.DateTime _
		)

			MyBase.New()

			Started = _Started
			Matcher = _Matcher
			Sources = _Sources
			CommandClasses = _CommandClasses
			InterrogatedCommands = _InterrogatedCommands
			Finished = _Finished

		End Sub

		''' <summary>Parametered Constructor (7 Parameters)</summary>
		Public Sub New( _
			ByVal _Started As System.DateTime, _
			ByVal _Matcher As ICommandsMatcher, _
			ByVal _Sources As ICommandsProvider(), _
			ByVal _CommandClasses As CommandInterrogatedClass(), _
			ByVal _InterrogatedCommands As CommandInterrogated(), _
			ByVal _Finished As System.DateTime, _
			ByVal _Loaded As System.DateTime _
		)

			MyBase.New()

			Started = _Started
			Matcher = _Matcher
			Sources = _Sources
			CommandClasses = _CommandClasses
			InterrogatedCommands = _InterrogatedCommands
			Finished = _Finished
			Loaded = _Loaded

		End Sub

	#End Region

	#Region " Class Plumbing/Interface Code "

		#Region " Settable Implementation "

			#Region " Public Methods "

				Public Function SetStarted(_Started As System.DateTime) As AssemblyConfig

					Started = _Started
					Return Me

				End Function

				Public Function SetMatcher(_Matcher As ICommandsMatcher) As AssemblyConfig

					Matcher = _Matcher
					Return Me

				End Function

				Public Function SetSources(_Sources As ICommandsProvider()) As AssemblyConfig

					Sources = _Sources
					Return Me

				End Function

				Public Function SetCommandClasses(_CommandClasses As CommandInterrogatedClass()) As AssemblyConfig

					CommandClasses = _CommandClasses
					Return Me

				End Function

				Public Function SetInterrogatedCommands(_InterrogatedCommands As CommandInterrogated()) As AssemblyConfig

					InterrogatedCommands = _InterrogatedCommands
					Return Me

				End Function

				Public Function SetFinished(_Finished As System.DateTime) As AssemblyConfig

					Finished = _Finished
					Return Me

				End Function

				Public Function SetLoaded(_Loaded As System.DateTime) As AssemblyConfig

					Loaded = _Loaded
					Return Me

				End Function

			#End Region

		#End Region

	#End Region

	#Region " Public Constants "

		''' <summary>Public Shared Reference to the Name of the Property: Started</summary>
		''' <remarks></remarks>
		Public Const PROPERTY_STARTED As String = "Started"

		''' <summary>Public Shared Reference to the Name of the Property: Matcher</summary>
		''' <remarks></remarks>
		Public Const PROPERTY_MATCHER As String = "Matcher"

		''' <summary>Public Shared Reference to the Name of the Property: Sources</summary>
		''' <remarks></remarks>
		Public Const PROPERTY_SOURCES As String = "Sources"

		''' <summary>Public Shared Reference to the Name of the Property: CommandClasses</summary>
		''' <remarks></remarks>
		Public Const PROPERTY_COMMANDCLASSES As String = "CommandClasses"

		''' <summary>Public Shared Reference to the Name of the Property: InterrogatedCommands</summary>
		''' <remarks></remarks>
		Public Const PROPERTY_INTERROGATEDCOMMANDS As String = "InterrogatedCommands"

		''' <summary>Public Shared Reference to the Name of the Property: Finished</summary>
		''' <remarks></remarks>
		Public Const PROPERTY_FINISHED As String = "Finished"

		''' <summary>Public Shared Reference to the Name of the Property: Loaded</summary>
		''' <remarks></remarks>
		Public Const PROPERTY_LOADED As String = "Loaded"

	#End Region

	#Region " Private Variables "

		''' <summary>Private Data Storage Variable for Property: Started</summary>
		''' <remarks></remarks>
		Private m_Started As System.DateTime

		''' <summary>Private Data Storage Variable for Property: Matcher</summary>
		''' <remarks></remarks>
		Private m_Matcher As ICommandsMatcher

		''' <summary>Private Data Storage Variable for Property: Sources</summary>
		''' <remarks></remarks>
		Private m_Sources As ICommandsProvider()

		''' <summary>Private Data Storage Variable for Property: CommandClasses</summary>
		''' <remarks></remarks>
		Private m_CommandClasses As CommandInterrogatedClass()

		''' <summary>Private Data Storage Variable for Property: InterrogatedCommands</summary>
		''' <remarks></remarks>
		Private m_InterrogatedCommands As CommandInterrogated()

		''' <summary>Private Data Storage Variable for Property: Finished</summary>
		''' <remarks></remarks>
		Private m_Finished As System.DateTime

		''' <summary>Private Data Storage Variable for Property: Loaded</summary>
		''' <remarks></remarks>
		Private m_Loaded As System.DateTime

	#End Region

	#Region " Public Properties "

		''' <summary>Provides Access to the Property: Started</summary>
		''' <remarks></remarks>
		Public Property Started() As System.DateTime
			Get
				Return m_Started
			End Get
			Set(value As System.DateTime)
				m_Started = value
			End Set
		End Property

		''' <summary>Provides Access to the Property: Matcher</summary>
		''' <remarks></remarks>
		<Leviathan.Configuration.Configurable("Matcher")> _
		Public Property Matcher() As ICommandsMatcher
			Get
				Return m_Matcher
			End Get
			Set(value As ICommandsMatcher)
				m_Matcher = value
			End Set
		End Property

		''' <summary>Provides Access to the Property: Sources</summary>
		''' <remarks></remarks>
		<Leviathan.Configuration.Configurable("Sources")> _
		Public Property Sources() As ICommandsProvider()
			Get
				Return m_Sources
			End Get
			Set(value As ICommandsProvider())
				m_Sources = value
			End Set
		End Property

		''' <summary>Provides Access to the Property: CommandClasses</summary>
		''' <remarks></remarks>
		Public Property CommandClasses() As CommandInterrogatedClass()
			Get
				Return m_CommandClasses
			End Get
			Set(value As CommandInterrogatedClass())
				m_CommandClasses = value
			End Set
		End Property

		''' <summary>Provides Access to the Property: InterrogatedCommands</summary>
		''' <remarks></remarks>
		Public Property InterrogatedCommands() As CommandInterrogated()
			Get
				Return m_InterrogatedCommands
			End Get
			Set(value As CommandInterrogated())
				m_InterrogatedCommands = value
			End Set
		End Property

		''' <summary>Provides Access to the Property: Finished</summary>
		''' <remarks></remarks>
		Public Property Finished() As System.DateTime
			Get
				Return m_Finished
			End Get
			Set(value As System.DateTime)
				m_Finished = value
			End Set
		End Property

		''' <summary>Provides Access to the Property: Loaded</summary>
		''' <remarks></remarks>
		Public Property Loaded() As System.DateTime
			Get
				Return m_Loaded
			End Get
			Set(value As System.DateTime)
				m_Loaded = value
			End Set
		End Property

	#End Region

End Class