Namespace Collections

	''' <summary>This attribute should declare the Type of object that is encapsulated by the collection.</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:40:40</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Collections\Attributes\ElementTypeAttribute.tt</generator-source>
	''' <generator-template>Text-Templates\Classes\VB_Object.tt</generator-template>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Collections\Attributes\ElementTypeAttribute.tt", "1")> _
	<AttributeUsageAttribute(AttributeTargets.[Class], _
		AllowMultiple:=False, Inherited:=False)> _
	Partial Public NotInheritable Class ElementTypeAttribute
		Inherits Attribute

		#Region " Public Constructors "

			''' <summary>Default Constructor</summary>
			Public Sub New()

				MyBase.New()

			End Sub

			''' <summary>Parametered Constructor (1 Parameters)</summary>
			Public Sub New( _
				ByVal _Type As System.Type _
			)

				MyBase.New()

				[Type] = _Type

			End Sub

		#End Region

		#Region " Class Plumbing/Interface Code "

			#Region " Attributable Implementation "

				#Region " Public Shared Methods "

					Public Shared Function GetMember( _
						ByVal onType As Type _
					) As Leviathan.Inspection.MemberAnalyser

						Return GetSingleObject(GetMembers(onType))

					End Function

					Public Shared Function GetMembers( _
						ByVal onType As Type _
					) As Leviathan.Inspection.MemberAnalyser()

						Return Leviathan.Inspection.TypeAnalyser.GetInstance(onType) _
							.ExecuteQuery(Leviathan.Inspection.AnalyserQuery.QUERY_MEMBERS_READABLE _
								.SetPresentAttribute(GetType(ElementTypeAttribute)) _
						)

					End Function

				#End Region

			#End Region

		#End Region

		#Region " Public Constants "

			''' <summary>Public Shared Reference to the Name of the Property: Type</summary>
			''' <remarks></remarks>
			Public Const PROPERTY_TYPE As String = "Type"

		#End Region

		#Region " Private Variables "

			''' <summary>Private Data Storage Variable for Property: Type</summary>
			''' <remarks></remarks>
			Private m_Type As System.Type

		#End Region

		#Region " Public Properties "

			''' <summary>Provides Access to the Property: Type</summary>
			''' <remarks></remarks>
			Public Property [Type]() As System.Type
				Get
					Return m_Type
				End Get
				Set(value As System.Type)
					m_Type = value
				End Set
			End Property

		#End Region

	End Class

End Namespace