Namespace Visualisation

	''' <summary>Enum to Hold Information Types</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:53:38</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Visualisation\Enums\InformationType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Visualisation\Enums\InformationType.tt", "1")> _
	Public Enum InformationType As System.Int32

		''' <summary>Indicating the Information is of No Type (e.g. it's an empty string or just blanks).</summary>
		None = 0

		''' <summary>Indicating the Information is of a General Type.</summary>
		General = 1

		''' <summary>Indicating the Information is relating to Performance information.</summary>
		Performance = 2

		''' <summary>Indicating the Information represents a Success.</summary>
		Success = 3

		''' <summary>Indicating the Information is Informational.</summary>
		Information = 4

		''' <summary>Indicating the Information is a Warning.</summary>
		Warning = 5

		''' <summary>Indicating the Information is an Error.</summary>
		[Error] = 6

		''' <summary>Indicating the Information is a Question.</summary>
		Question = 7

		''' <summary>Indicating the Information is a Log.</summary>
		Log = 8

		''' <summary>Indicating the Information is a Debug.</summary>
		Debug = 9

		''' <summary>Indicating the Information is Help.</summary>
		Help = 10

	End Enum

End Namespace