Namespace Commands

	''' <summary>Enum Representing Command Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:43:36</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Commands\Enums\CommandType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Commands\Enums\CommandType.tt", "1")> _
	Public Enum CommandType As System.Int32

		''' <summary>No Type Clearly Indentified.</summary>
		Unknown = 0

		''' <summary>A Transformation command should transform objects and return the results, e.g. Mathmatical Functions, Set Correlations, Duplicate Removals, Aggregations etc. This could also include calls to a persistance layer.</summary>
		Transform = 1

		''' <summary>A Format command should prepare objects for Outputting.</summary>
		Format = 2

		''' <summary>An Output Command should output Formatted Objects.</summary>
		Output = 3

		''' <summary>A Process Command should return a Boolean indicating Success/Failure for the Process.</summary>
		Process = 4

		''' <summary>A Retrieval Command should return objects but not take any parameters (e.g. a cache enumeration)</summary>
		Retrieval = 5

	End Enum

End Namespace