Namespace Commands

	''' <summary>Enum Representing Outputted Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:43:37</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Commands\Enums\OutputtedType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Commands\Enums\OutputtedType.tt", "1")> _
	Public Enum OutputtedType As System.Int32

		''' <summary>Message</summary>
		Message = 1

		''' <summary>Messages</summary>
		Messages = 2

		''' <summary>PropertyValueCube</summary>
		PropertyValueCube = 3

	End Enum

End Namespace