Namespace Commands

	''' <summary>Enum to SQL Connection Ownership Details</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:43:37</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Commands\Enums\SqlConnectionOwnership.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Commands\Enums\SqlConnectionOwnership.tt", "1")> _
	Public Enum SqlConnectionOwnership As System.Int32

		''' <summary>Indicating the Connection is Internally Owned by the Method.</summary>
		Internal = 0

		''' <summary>Indicating the Connection is Externally Owned.</summary>
		External = 1

	End Enum

End Namespace