Namespace Commands

	''' <summary>Enum representing Key that is being previewed/pressed..</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:43:38</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Commands\Enums\SuggestedCommandKey.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Commands\Enums\SuggestedCommandKey.tt", "1")> _
	Public Enum SuggestedCommandKey As System.Int32

		''' <summary>None</summary>
		Input = 0

		''' <summary>Help Key (Normally F1)</summary>
		Help = 1

		''' <summary>Tab Key (e.g. Move on to the Next Part of the Command)</summary>
		Tab = 2

		''' <summary>Up Key (e.g. Cycle through Alternatives)</summary>
		Up = 3

		''' <summary>Down Key (e.g. Cycle through Alternatives)</summary>
		Down = 4

		''' <summary>Right Key</summary>
		Right = 5

		''' <summary>Enter Key</summary>
		Enter = 6

		''' <summary>Reversed Tab Key (e.g. Move on to the Previous Part of the Command)</summary>
		ReverseTab = 7

	End Enum

End Namespace