Namespace Commands

	''' <summary>Enum Representing Value Type (for Pivoting)</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:43:39</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Commands\Enums\ValueType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Commands\Enums\ValueType.tt", "1")> _
	Public Enum ValueType As System.Int32

		''' <summary>Value</summary>
		Value = 0

		''' <summary>Count</summary>
		Count = 1

		''' <summary>Sum</summary>
		Sum = 2

		''' <summary>Average</summary>
		Average = 3

		''' <summary>Present</summary>
		Present = 4

		''' <summary>NotPresent</summary>
		NotPresent = 5

		''' <summary>Max</summary>
		Max = 6

		''' <summary>Min</summary>
		Min = 7

		''' <summary>Percentage</summary>
		Percentage = 9

		''' <summary>BackgroundPresent</summary>
		BackgroundPresent = 10

	End Enum

End Namespace