Namespace Commands

	''' <summary>Enum for Verbosity Levels</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>10/02/2014 15:43:39</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Leviathan\_Commands\Enums\VerbosityLevel.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Leviathan\_Commands\Enums\VerbosityLevel.tt", "1")> _
	Public Enum VerbosityLevel As System.Int32

		''' <summary>No Verbosity (No/Minimal Output).</summary>
		Silent = 1

		''' <summary>Errors Only Verbosity (Show Errors Output).</summary>
		Errors = 2

		''' <summary>Standard Verbosity (Normal Level of Output).</summary>
		Standard = 3

		''' <summary>Interactive Verbosity (Real-Time Level of Output).</summary>
		Interactive = 4

		''' <summary>High Verbosity (High Level of Output).</summary>
		Verbose = 5

		''' <summary>Debug Verbosity (Top Level of Output).</summary>
		Debug = 6

	End Enum

End Namespace